name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: '3.11'
      - name: "Install python dependencies"
        run: |
          pip install -r requirements_test.txt
      - name: "Run tests"
        run: |
          pytest
